version: '3.7'
services:
  saml2:
    image: saml2
    build: saml2
    ports:
      - 8180:8180
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost:8080/auth/realms/internal
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:8080/auth/realms/internal/broker/saml/endpoint
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:8080/auth/realms/internal/broker/saml/endpoint
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
  keycloak:
    image: jboss/keycloak:6.0.1
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: h2
    ports:
      - 8080:8080
  keycloak-config:
    image: keycloak-config
    build: keycloak-config
    depends_on:
      - keycloak
      - saml2
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_CLIENT_ID: admin-cli
      KEYCLOAK_REALM: master
      WAIT_FOR_KEYCLOAK: curl -f -s -o /dev/null http://keycloak:8080/auth/admin
