version: '3'
services:
  testsamlidp_idp:
    build: .
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID:
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE:
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE:
      SIMPLESAMLPHP_ADMIN_PASSWORD:
      SIMPLESAMLPHP_SECRET_SALT:
    ports:
    - "8081:8081"
    - "8443:8443"
    #volumes:
    #- /users.php:/var/www/simplesamlphp/config/simplesamlphp/authsources.php
