version: '3.7'
services:
  saml2:
    image: saml2
    build: saml2
    ports:
      - 8180:8180
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost/auth/realms/internal
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost/auth/realms/internal/broker/saml/endpoint
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost/auth/realms/internal/broker/saml/endpoint
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
  keycloak:
    image: jboss/keycloak:6.0.1
    depends_on:
      - mysql
    labels:
      - "traefik.http.routers.keycloak.rule=PathPrefix(`/`)"
      - "traefik.http.services.keycloak-service.loadbalancer.server.port=8080"
    volumes:
      - ./keycloak/infinispan-work.cli:/opt/jboss/startup-scripts/infinispan-work.cli
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_PROPERTIES: "datasource_jndi_name=java:jboss/datasources/KeycloakDS"
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  keycloak-lb:
    image: keycloak-lb
    build: keycloak-lb
    ports:
      - 80:80
    depends_on:
      - keycloak
    environment:
      WAIT_FOR_KEYCLOAK: curl -f -s -o /dev/null http://keycloak:8080/auth/admin
      RETRIES_COUNT: 20
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./keycloak-config/scripts/wait-for.sh:/opt/wait-for.sh
    entrypoint: /opt/wait-for.sh
    command:
      - "/entrypoint.sh"
      - "traefik"
      - "--providers.docker"
      - "--accesslog=true"
  keycloak-config:
    image: keycloak-config
    build: keycloak-config
    depends_on:
      - keycloak-lb
      - saml2
    environment:
      KEYCLOAK_URL: http://keycloak-lb
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_CLIENT_ID: admin-cli
      KEYCLOAK_REALM: master
      RETRIES_COUNT: 20
      WAIT_FOR_KEYCLOAK: curl -f -s -o /dev/null http://keycloak-lb/auth/admin
  test:
    image: test
    build: k6
    network_mode: host
    depends_on:
      - keycloak-config
    volumes:
      - ./keycloak-config/scripts/wait-for.sh:/opt/wait-for.sh
      - ./k6/test.js:/opt/test.js
    environment:
      RETRIES_COUNT: 30
      WAIT_FOR_KEYCLOAK_LB: curl -f -s -o /dev/null http://localhost/auth/admin
    entrypoint: /opt/wait-for.sh
    command: k6 run -u 10 -d 30s /opt/test.js
